name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # Ensure the version matches your project

      - name: Restore dependencies
        run: dotnet restore ./Personnummer-main/PersonnummerKontroll.csproj

      - name: Build the solution
        run: dotnet build ./Personnummer-main/PersonnummerKontroll.csproj --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test ./Personnummer-main/PersonnummerKontroll.Tests/PersonnummerKontroll.Tests.csproj --no-restore --verbosity normal



name: Run tests
      run: dotnet test ./Personnummer-main/Personnummer-main/PersonnummerKontroll.Tests/PersonnummerKontroll.Tests.csproj --no-restore --verbosity normal
