on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger this workflow on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the build on the latest Ubuntu VM

    steps:
      # Step 1: Checkout the code from your repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET 8.0 SDK
      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'  # Specify the .NET version you're using

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./personnummerkontroll  # Update with the relative path to the directory with your .csproj or .sln file

      # Step 4: Build the project
      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./personnummerkontroll  # Update with the relative path to the directory with your .csproj or .sln file

      # Step 5: Run the tests
      - name: Run tests
        run: dotnet test --configuration Release
        working-directory: ./personnummerkontroll  # Update with the relative path to the directory with your .csproj or .sln file
