name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      run: |
        echo "${{ secrets.GROUP5_PASSWORD }}" | docker login -u "${{ secrets.GROUP5_USERNAME }}" --password-stdin

    # Step 3: Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.GROUP5_USERNAME }}/personnummer-validation:latest .

    # Step 4: Push Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.GROUP5_USERNAME }}/personnummer-validation:latest
