name: Publish Docker Image to GitHub Container Registry

on:
  push:
    branches:
    - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      run: echo $GHCR_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        set -e
        IMAGE_NAME=ghcr.io/Abdullahi-El/personnummerkontrol-docker
        docker build -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:latest
