name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up .NET SDK (you can change version if necessary)
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    # Step 3: Restore dependencies and build the project
    - name: Restore and build
      run: |
        dotnet restore
        echo '-----------------------------'
        dotnet build

    # Step 4: Log in to DockerHub using GitHub Secrets
    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Step 5: Build Docker image
    - name: Build and push Docker image
      run: |
        docker build -t abdullahielmi/docker-intro-gh:${{ github.sha }} .
        docker push abdullahielmi/docker-intro-gh:${{ github.sha }}
